import type { ITenant } from './tenant.types';

export const MOCK_TENANTS: ITenant[] = [
  {
    id: 't-hq',
    code: 'HQ',
    name: 'Trụ sở chính',
    type: 'hq',
    status: 'active',
    city: 'TP. Hồ Chí Minh',
    address: '123 Nguyễn Huệ, Phường Bến Nghé, Quận 1',
    phone: '028 3823 4567',
    email: 'hq@comforty.vn',
    managerName: 'Trần Minh Khoa',
    openedAt: '2018-06-15',
    userCount: 14,
    warehouseCount: 1,
  },
  {
    id: 't-q1',
    code: 'Q1',
    name: 'Chi nhánh Quận 1',
    type: 'store',
    status: 'active',
    city: 'TP. Hồ Chí Minh',
    address: '45 Lê Lợi, Phường Bến Thành, Quận 1',
    phone: '028 3914 1122',
    email: 'q1@comforty.vn',
    managerName: 'Nguyễn Thị Hằng',
    openedAt: '2019-03-10',
    userCount: 6,
    warehouseCount: 1,
  },
  {
    id: 't-q7',
    code: 'Q7',
    name: 'Chi nhánh Quận 7',
    type: 'store',
    status: 'active',
    city: 'TP. Hồ Chí Minh',
    address: '88 Nguyễn Thị Thập, Phường Tân Phú, Quận 7',
    phone: '028 5417 2233',
    email: 'q7@comforty.vn',
    managerName: 'Phạm Quốc Cường',
    openedAt: '2020-08-22',
    userCount: 5,
    warehouseCount: 1,
  },
  {
    id: 't-td',
    code: 'TD',
    name: 'Chi nhánh Thủ Đức',
    type: 'store',
    status: 'active',
    city: 'TP. Hồ Chí Minh',
    address: '210 Võ Văn Ngân, Phường Linh Chiểu, TP. Thủ Đức',
    phone: '028 3722 8899',
    email: 'thuduc@comforty.vn',
    managerName: 'Lê Hoàng Nam',
    openedAt: '2021-11-05',
    userCount: 4,
    warehouseCount: 1,
  },
  {
    id: 't-hk',
    code: 'HK',
    name: 'Chi nhánh Hoàn Kiếm',
    type: 'store',
    status: 'active',
    city: 'Hà Nội',
    address: '72 Hàng Bài, Phường Hàng Bài, Quận Hoàn Kiếm',
    phone: '024 3936 5577',
    email: 'hoankiem@comforty.vn',
    managerName: 'Đỗ Thu Trang',
    openedAt: '2022-04-18',
    userCount: 5,
    warehouseCount: 1,
  },
  {
    id: 't-hc',
    code: 'HC',
    name: 'Chi nhánh Hải Châu',
    type: 'store',
    status: 'inactive',
    city: 'Đà Nẵng',
    address: '15 Trần Phú, Phường Hải Châu I, Quận Hải Châu',
    phone: '0236 3821 4455',
    email: 'haichau@comforty.vn',
    managerName: 'Võ Minh Tuấn',
    openedAt: '2023-01-12',
    userCount: 3,
    warehouseCount: 1,
  },
];

export const DEFAULT_TENANT_ID = 't-q1';

export function findTenant(id: string): ITenant | undefined {
  return MOCK_TENANTS.find((t) => t.id === id);
}
